DATA WORK.VC_IRVINE_2014;
	SET WORK.CRIME_DATA;
	WHERE CITY='IRVINE' AND YEAR=2014;
	Rapes=INPUT(RAPE,5.);
	KEEP RAPES MURDER AGGRAVATED_ASSULT ROBBERY;
RUN;

PROC TRANSPOSE DATA=WORK.VC_IRVINE_2014
	OUT=WORK.VC_IRVINE_2014_TRP
	NAME=VIOLENT_CRIMES;
RUN;

DATA WORK.VC_IRVINE_2014_TRP;
	SET WORK.VC_IRVINE_2014_TRP;
	YEAR=2014;
	RENAME COL1=COUNT;
	DROP _LABEL_;
RUN;

DATA WORK.VC_IRVINE_2015;
	SET WORK.CRIME_DATA;
	WHERE CITY='IRVINE' AND YEAR=2015;
	Rapes=INPUT(RAPE,5.);
	KEEP RAPES MURDER AGGRAVATED_ASSULT ROBBERY;
RUN;

PROC TRANSPOSE DATA=WORK.VC_IRVINE_2015
	OUT=WORK.VC_IRVINE_2015_TRP
	NAME=VIOLENT_CRIMES;
RUN;

DATA WORK.VC_IRVINE_2015_TRP;
	SET WORK.VC_IRVINE_2015_TRP;
	YEAR=2015;
	RENAME COL1=COUNT;
	DROP _LABEL_;
RUN;


PROC APPEND BASE=WORK.VC_IRVINE_2014_TRP
	DATA=WORK.VC_IRVINE_2015_TRP FORCE;
RUN;

PROC SGPLOT DATA = VC_IRVINE_2014_TRP;
	VBAR VIOLENT_CRIMES / RESPONSE = COUNT GROUP = YEAR GROUPDISPLAY=CLUSTER DATASKIN=MATTE;
	YAXIS LABEL='No of Crimes';
	XAXIS LABEL='Violent Crimes';
	TITLE1 'IRVINE, CA';
	TITLE2 'Variation of crimes by year';
RUN;
QUIT;
