/*data set for Murrieta for the year 2014*/
DATA WORK.VC_MURRIETA_2014;
	SET WORK.CRIME_DATA;
	WHERE CITY='MURRIETA' AND YEAR=2014;
	Rapes=INPUT(RAPE,5.);
	KEEP RAPES MURDER AGGRAVATED_ASSULT ROBBERY;
RUN;

/*transpose to get violent crimes in a variable*/
PROC TRANSPOSE DATA=WORK.VC_MURRIETA_2014
	OUT=WORK.VC_MURRIETA_2014_TRP
	NAME=VIOLENT_CRIMES;
RUN;

/*add the year as variable*/
DATA WORK.VC_MURRIETA_2014_TRP;
	SET WORK.VC_MURRIETA_2014_TRP;
	YEAR=2014;
	RENAME COL1=COUNT;
	DROP _LABEL_;
RUN;

/*data set for Murrieta for the year 2015*/
DATA WORK.VC_MURRIETA_2015;
	SET WORK.CRIME_DATA;
	WHERE CITY='MURRIETA' AND YEAR=2015;
	Rapes=INPUT(RAPE,5.);
	KEEP RAPES MURDER AGGRAVATED_ASSULT ROBBERY;
RUN;

/*transpose to get the violent crimes in a single variable*/
PROC TRANSPOSE DATA=WORK.VC_MURRIETA_2015
	OUT=WORK.VC_MURRIETA_2015_TRP
	NAME=VIOLENT_CRIMES;
RUN;

/*add the year variable*/
DATA WORK.VC_MURRIETA_2015_TRP;
	SET WORK.VC_MURRIETA_2015_TRP;
	YEAR=2015;
	RENAME COL1=COUNT;
	DROP _LABEL_;
RUN;

/*append the data sets to get the number of crimes
in both the years*/
PROC APPEND BASE=WORK.VC_MURRIETA_2014_TRP
	DATA=WORK.VC_MURRIETA_2015_TRP FORCE;
RUN;

/*bar charts to visualise the number of crimes in boh the years*/
PROC SGPLOT DATA = VC_MURRIETA_2014_TRP;
	VBAR VIOLENT_CRIMES / RESPONSE = COUNT GROUP = YEAR GROUPDISPLAY=CLUSTER DATASKIN=MATTE;
	YAXIS LABEL='No of Crimes';
	XAXIS LABEL='Violent Crimes';
	TITLE1 'MURRIETA, CA';
	TITLE2 'Variation of crimes by year';
RUN;
QUIT;
