/*data set for stockton in the year 2014*/
DATA WORK.VC_STOCKTON_2014;
	SET WORK.CRIME_DATA;
	WHERE CITY='STOCKTON' AND YEAR=2014;
	Rapes=INPUT(RAPE,5.);
	KEEP RAPES MURDER AGGRAVATED_ASSULT ROBBERY;
RUN;

/*Transpose data to get violent crimes as variable*/
PROC TRANSPOSE DATA=WORK.VC_STOCKTON_2014
	OUT=WORK.VC_STOCKTON_2014_TRP
	NAME=VIOLENT_CRIMES;
RUN;

/*Add the year variable*/
DATA WORK.VC_STOCKTON_2014_TRP;
	SET WORK.VC_STOCKTON_2014_TRP;
	YEAR=2014;
	RENAME COL1=COUNT;
	DROP _LABEL_;
RUN;

/*data set for stockton in the year 2015*/
DATA WORK.VC_STOCKTON_2015;
	SET WORK.CRIME_DATA;
	WHERE CITY='STOCKTON' AND YEAR=2015;
	Rapes=INPUT(RAPE,5.);
	KEEP RAPES MURDER AGGRAVATED_ASSULT ROBBERY;
RUN;

/*transpose to get violent crimes in a variable*/
PROC TRANSPOSE DATA=WORK.VC_STOCKTON_2015
	OUT=WORK.VC_STOCKTON_2015_TRP
	NAME=VIOLENT_CRIMES;
RUN;

/*add year to the data set*/
DATA WORK.VC_STOCKTON_2015_TRP;
	SET WORK.VC_STOCKTON_2015_TRP;
	YEAR=2015;
	RENAME COL1=COUNT;
	DROP _LABEL_;
RUN;

/*Append the data sets to get the number
detaails of each violent crime in both the years*/
PROC APPEND BASE=WORK.VC_STOCKTON_2014_TRP
	DATA=WORK.VC_STOCKTON_2015_TRP FORCE;
RUN;

/*bar chart for the violetn crimes by year*/
PROC SGPLOT DATA = VC_STOCKTON_2014_TRP;
	VBAR VIOLENT_CRIMES / RESPONSE = COUNT GROUP = YEAR GROUPDISPLAY=CLUSTER DATASKIN=MATTE;
	YAXIS LABEL='No of Crimes';
	XAXIS LABEL='Violent Crimes';
	TITLE1 'Stockton, CA';
	TITLE2 'Variation of crimes by year';
RUN;
QUIT;
