/*Add total crime variable to the data set*/
DATA WORK.CRIME_DATA_STATE;
	SET WORK.CRIME_DATA;
	TOTAL_CRIME=VIOLENT_CRIME+PROPERTY_CRIME;
RUN;

/*data set to have population and total crime by state*/
PROC SQL;
	CREATE TABLE WORK.MAP_2014 AS
	SELECT STATE, STATE_CODE, YEAR, SUM(POPULATION) AS POPULATION,
	SUM(TOTAL_CRIME) AS TOTAL_CRIME
	FROM WORK.CRIME_DATA_STATE
	WHERE YEAR=2014
	GROUP BY STATE,STATE_CODE,YEAR;
QUIT;

/*set total_crime for hawaii state same as the year 2015*/	
DATA WORK.MAP_2014;
	SET WORK.MAP_2014;
	IF STATE='HAWAII' AND YEAR=2014 THEN
	TOTAL_CRIME=14994;
	CRIME_RATE=(TOTAL_CRIME/POPULATION)*100000;
	DROP YEAR;
RUN;

PROC PRINT DATA=WORK.MAP_2014 LABEL;
	FORMAT POPULATION TOTAL_CRIME COMMA16.
	CRIME_RATE COMMA16.3;
	LABEL STATE_CODE='State Code'
	POPULATION='Population' TOTAL_CRIME='Total Crimes'
	CRIME_RATE='Crime Rate';
TITLE1 'United States: Year 2014';
TITLE2 'Crime Rate by State';
TITLE3 '**Crime rate per 100,000';
RUN;
	

/*data set to have population and total crime by state*/
PROC SQL;
	CREATE TABLE WORK.MAP_2015 AS
	SELECT STATE, STATE_CODE, YEAR, SUM(POPULATION) AS POPULATION,
	SUM(TOTAL_CRIME) AS TOTAL_CRIME
	FROM WORK.CRIME_DATA_STATE
	WHERE YEAR=2015
	GROUP BY STATE,STATE_CODE,YEAR;
QUIT;

DATA WORK.MAP_2015;
	SET WORK.MAP_2015;
	CRIME_RATE=(TOTAL_CRIME/POPULATION)*100000;
	DROP YEAR;
RUN;


PROC PRINT DATA=WORK.MAP_2015 LABEL;
	FORMAT POPULATION TOTAL_CRIME COMMA16.
	CRIME_RATE COMMA16.3;
	LABEL STATE_CODE='State Code'
	POPULATION='Population' TOTAL_CRIME='Total Crimes'
	CRIME_RATE='Crime Rate';
TITLE1 'United States: Year 2015';
TITLE2 'Crime Rate by State';
TITLE3 '**Crime rate per 100,000';
RUN;



