/*data set for SANFRANCISCO in the year 2014*/
DATA WORK.PC_SANFRANCISCO_2014;
	SET WORK.CRIME_DATA;
	WHERE CITY='SAN FRANCISCO' AND YEAR=2014;
	KEEP BURGLARY LARCENY_THEFT MOTOR_VEHICLE_THEFT;
RUN;

/*Transpose data to get violent crimes as variable*/
PROC TRANSPOSE DATA=WORK.PC_SANFRANCISCO_2014
	OUT=WORK.PC_SANFRANCISCO_2014_TRP
	NAME=PROPERTY_CRIMES;
RUN;

/*Add the year variable*/
DATA WORK.PC_SANFRANCISCO_2014_TRP;
	SET WORK.PC_SANFRANCISCO_2014_TRP;
	YEAR=2014;
	RENAME COL1=COUNT;
	DROP _LABEL_;
RUN;

/*data set for SANFRANCISCO in the year 2015*/
DATA WORK.PC_SANFRANCISCO_2015;
	SET WORK.CRIME_DATA;
	WHERE CITY='SAN FRANCISCO' AND YEAR=2015;
	KEEP BURGLARY LARCENY_THEFT MOTOR_VEHICLE_THEFT;
RUN;

/*transpose to get violent crimes in a variable*/
PROC TRANSPOSE DATA=WORK.PC_SANFRANCISCO_2015
	OUT=WORK.PC_SANFRANCISCO_2015_TRP
	NAME=PROPERTY_CRIMES;
RUN;

/*add year to the data set*/
DATA WORK.PC_SANFRANCISCO_2015_TRP;
	SET WORK.PC_SANFRANCISCO_2015_TRP;
	YEAR=2015;
	RENAME COL1=COUNT;
	DROP _LABEL_;
RUN;

/*Append the data sets to get the number
detaails of each violent crime in both the years*/
PROC APPEND BASE=WORK.PC_SANFRANCISCO_2014_TRP
	DATA=WORK.PC_SANFRANCISCO_2015_TRP FORCE;
RUN;

/*bar chart for the violetn crimes by year*/
PROC SGPLOT DATA = PC_SANFRANCISCO_2014_TRP;
	VBAR PROPERTY_CRIMES / RESPONSE = COUNT GROUP = YEAR GROUPDISPLAY=CLUSTER DATASKIN=MATTE;
	YAXIS LABEL='No of Crimes';
	XAXIS LABEL='Property Crimes';
	TITLE1 'San Francisco, CA';
	TITLE2 'Variation of crimes by year';
RUN;
QUIT;
